### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Overloot** [Overloot/ARLG#3]
На задачи можно не ориентироваться. Рефакторинг превратился в нечто большее. 
Все вопросы, задачи, планы и т.д. определяются по скайпу.

**Comment by devapromix** [comment]
Привет! Давно это было :)

**Comment by Overloot** [comment]
> Привет! Давно это было :)

о! привет! давно было, вот зашел случайно и обратил внимание, что issue есть открытое)) решил закрыть))))
